from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
INSTALL_STATE_PATH = PROJECT_ROOT / ".transithub-install-state.json"
DOCS_DIR = PROJECT_ROOT / "docs"
INSTALL_DIR = PROJECT_ROOT / "install"
INSTALL_HOST_DIR = INSTALL_DIR / "host"
SERVICE_NGINX_DIR = PROJECT_ROOT / "nginx"
SERVICE_NGINX_CONFIG_DIR = SERVICE_NGINX_DIR / "config"
SERVICE_NGINX_EXTENSIONS_DIR = SERVICE_NGINX_DIR / "extensions"
SERVICE_XUI_DIR = PROJECT_ROOT / "xui"
SERVICE_XUI_DATA_DIR = SERVICE_XUI_DIR / "data"
SERVICE_SUBCONVERTER_DIR = PROJECT_ROOT / "subconverter"
SERVICE_SUBCONVERTER_DATA_DIR = SERVICE_SUBCONVERTER_DIR / "data"
SERVICE_TGPROXY_DIR = PROJECT_ROOT / "tgproxy"
SERVICE_TGPROXY_CONFIG_PATH = SERVICE_TGPROXY_DIR / "config.toml"
SERVICE_NETBIRD_DIR = PROJECT_ROOT / "netbird"
SERVICE_NETBIRD_DATA_DIR = SERVICE_NETBIRD_DIR / "data"
SERVICE_WEB_DIR = PROJECT_ROOT / "web"
SERVICE_CLIENT_PAGE_DIR = SERVICE_WEB_DIR / "client_page"
SERVICE_FAKE_SITE_DIR = SERVICE_WEB_DIR / "fake_site"
TEMPLATES_DIR = PROJECT_ROOT / "templates"
TEMPLATES_PROXY_DIR = TEMPLATES_DIR / "proxy"
TEMPLATES_TGPROXY_DIR = TEMPLATES_DIR / "tgproxy"
TEMPLATES_SUBPAGE_DIR = TEMPLATES_DIR / "subpage"
TEMPLATES_CLASH_DIR = TEMPLATES_DIR / "clash"
TEMPLATES_FAKESITE_DIR = TEMPLATES_DIR / "fakesite"
INSTANCE_ENV_PATH = PROJECT_ROOT / "instance.env"
INSTANCE_ENV_EXAMPLE_PATH = PROJECT_ROOT / "instance.env.example"
SERVICE_NGINX_COMPOSE_PATH = SERVICE_NGINX_DIR / "docker-compose.yml"
SERVICE_XUI_COMPOSE_PATH = SERVICE_XUI_DIR / "docker-compose.yml"
SERVICE_SUBCONVERTER_COMPOSE_PATH = SERVICE_SUBCONVERTER_DIR / "docker-compose.yml"
SERVICE_TGPROXY_COMPOSE_PATH = SERVICE_TGPROXY_DIR / "docker-compose.yml"
SERVICE_NETBIRD_COMPOSE_PATH = SERVICE_NETBIRD_DIR / "docker-compose.yml"
COMPOSE_FILES = [
    SERVICE_NGINX_COMPOSE_PATH,
    SERVICE_XUI_COMPOSE_PATH,
    SERVICE_SUBCONVERTER_COMPOSE_PATH,
    SERVICE_TGPROXY_COMPOSE_PATH,
    SERVICE_NETBIRD_COMPOSE_PATH,
]
HOST_PREPARE_STATUS_PATH = INSTALL_HOST_DIR / "last_prepare.json"

SERVICE_PROXY_DIR = SERVICE_NGINX_DIR
SERVICE_PROXY_CONFIG_DIR = SERVICE_NGINX_CONFIG_DIR
SERVICE_PROXY_EXTENSIONS_DIR = SERVICE_NGINX_EXTENSIONS_DIR


REQUIRED_DIRS = [
    INSTALL_DIR,
    INSTALL_HOST_DIR,
    SERVICE_NGINX_DIR,
    SERVICE_NGINX_CONFIG_DIR,
    SERVICE_NGINX_EXTENSIONS_DIR,
    SERVICE_XUI_DIR,
    SERVICE_XUI_DATA_DIR,
    SERVICE_SUBCONVERTER_DIR,
    SERVICE_SUBCONVERTER_DATA_DIR,
    SERVICE_TGPROXY_DIR,
    SERVICE_NETBIRD_DIR,
    SERVICE_NETBIRD_DATA_DIR,
    SERVICE_WEB_DIR,
    SERVICE_CLIENT_PAGE_DIR,
    SERVICE_FAKE_SITE_DIR,
    TEMPLATES_DIR,
    TEMPLATES_PROXY_DIR,
    TEMPLATES_TGPROXY_DIR,
    TEMPLATES_SUBPAGE_DIR,
    TEMPLATES_CLASH_DIR,
    TEMPLATES_FAKESITE_DIR,
]
