from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = PROJECT_ROOT / "docs"
LEGACY_RUNTIME_DIR = PROJECT_ROOT / "runtime"
LEGACY_RUNTIME_ENV_DIR = LEGACY_RUNTIME_DIR / "env"
LEGACY_RUNTIME_PROXY_DIR = LEGACY_RUNTIME_DIR / "proxy"
LEGACY_RUNTIME_PROXY_RENDERED_DIR = LEGACY_RUNTIME_PROXY_DIR / "rendered"
LEGACY_RUNTIME_PROXY_EXTENSIONS_DIR = LEGACY_RUNTIME_PROXY_DIR / "extensions"
LEGACY_RUNTIME_SUBPAGE_DIR = LEGACY_RUNTIME_DIR / "subpage"
LEGACY_RUNTIME_FAKESITE_DIR = LEGACY_RUNTIME_DIR / "fakesite"
LEGACY_RUNTIME_XUI_DATA_DIR = LEGACY_RUNTIME_DIR / "xui" / "data"
LEGACY_DEPLOY_DIR = PROJECT_ROOT / "deploy"
LEGACY_DEPLOY_ENV_DIR = LEGACY_DEPLOY_DIR / "env"
LEGACY_DEPLOY_SERVICES_DIR = LEGACY_DEPLOY_DIR / "services"
LEGACY_DEPLOY_PROXY_CONFIG_DIR = LEGACY_DEPLOY_SERVICES_DIR / "reverse-proxy" / "config"
LEGACY_DEPLOY_PROXY_EXTENSIONS_DIR = LEGACY_DEPLOY_SERVICES_DIR / "reverse-proxy" / "extensions"
LEGACY_DEPLOY_XUI_DATA_DIR = LEGACY_DEPLOY_SERVICES_DIR / "xui" / "data"
LEGACY_DEPLOY_SUBCONVERTER_DATA_DIR = LEGACY_DEPLOY_SERVICES_DIR / "subconverter" / "data"
LEGACY_DEPLOY_SUBPAGE_SITE_DIR = LEGACY_DEPLOY_SERVICES_DIR / "web-sub" / "site"
LEGACY_DEPLOY_FAKESITE_SITE_DIR = LEGACY_DEPLOY_SERVICES_DIR / "fake-site" / "site"
INSTALL_DIR = PROJECT_ROOT / "install"
INSTALL_HOST_DIR = INSTALL_DIR / "host"
SERVICE_NGINX_DIR = PROJECT_ROOT / "nginx"
SERVICE_NGINX_CONFIG_DIR = SERVICE_NGINX_DIR / "config"
SERVICE_NGINX_EXTENSIONS_DIR = SERVICE_NGINX_DIR / "extensions"
SERVICE_XUI_DIR = PROJECT_ROOT / "xui"
SERVICE_XUI_DATA_DIR = SERVICE_XUI_DIR / "data"
SERVICE_SUBCONVERTER_DIR = PROJECT_ROOT / "subconverter"
SERVICE_SUBCONVERTER_DATA_DIR = SERVICE_SUBCONVERTER_DIR / "data"
SERVICE_WEB_DIR = PROJECT_ROOT / "web"
SERVICE_CLIENT_PAGE_DIR = SERVICE_WEB_DIR / "client_page"
SERVICE_FAKE_SITE_DIR = SERVICE_WEB_DIR / "fake_site"
TEMPLATES_DIR = PROJECT_ROOT / "templates"
TEMPLATES_PROXY_DIR = TEMPLATES_DIR / "proxy"
TEMPLATES_SUBPAGE_DIR = TEMPLATES_DIR / "subpage"
TEMPLATES_CLASH_DIR = TEMPLATES_DIR / "clash"
TEMPLATES_FAKESITE_DIR = TEMPLATES_DIR / "fakesite"
INSTANCE_ENV_PATH = PROJECT_ROOT / "instance.env"
INSTANCE_ENV_EXAMPLE_PATH = PROJECT_ROOT / "instance.env.example"
SERVICE_NGINX_COMPOSE_PATH = SERVICE_NGINX_DIR / "docker-compose.yml"
SERVICE_XUI_COMPOSE_PATH = SERVICE_XUI_DIR / "docker-compose.yml"
SERVICE_SUBCONVERTER_COMPOSE_PATH = SERVICE_SUBCONVERTER_DIR / "docker-compose.yml"
COMPOSE_FILES = [
    SERVICE_NGINX_COMPOSE_PATH,
    SERVICE_XUI_COMPOSE_PATH,
    SERVICE_SUBCONVERTER_COMPOSE_PATH,
]
LEGACY_COMPOSE_PATH = PROJECT_ROOT / "compose.yaml"
HOST_PREPARE_STATUS_PATH = INSTALL_HOST_DIR / "last_prepare.json"
LEGACY_INSTANCE_ENV_PATH = LEGACY_RUNTIME_ENV_DIR / "instance.env"
LEGACY_DEPLOY_INSTANCE_ENV_PATH = LEGACY_DEPLOY_ENV_DIR / "instance.env"

SERVICE_PROXY_DIR = SERVICE_NGINX_DIR
SERVICE_PROXY_CONFIG_DIR = SERVICE_NGINX_CONFIG_DIR
SERVICE_PROXY_EXTENSIONS_DIR = SERVICE_NGINX_EXTENSIONS_DIR


REQUIRED_DIRS = [
    INSTALL_DIR,
    INSTALL_HOST_DIR,
    SERVICE_NGINX_DIR,
    SERVICE_NGINX_CONFIG_DIR,
    SERVICE_NGINX_EXTENSIONS_DIR,
    SERVICE_XUI_DIR,
    SERVICE_XUI_DATA_DIR,
    SERVICE_SUBCONVERTER_DIR,
    SERVICE_SUBCONVERTER_DATA_DIR,
    SERVICE_WEB_DIR,
    SERVICE_CLIENT_PAGE_DIR,
    SERVICE_FAKE_SITE_DIR,
    TEMPLATES_DIR,
    TEMPLATES_PROXY_DIR,
    TEMPLATES_SUBPAGE_DIR,
    TEMPLATES_CLASH_DIR,
    TEMPLATES_FAKESITE_DIR,
]
